export const ROUTES = {
  // Auth
  LOGIN: 'LOGIN',
  SIGNUP: 'SIGNUP',

  // Home
  HOME: 'HOME',

  // Medicamentos
  MEDICAMENTOS: 'MEDICAMENTOS',
  ADICIONAR_MEDICAMENTO: 'ADICIONAR_MEDICAMENTO',

  // Agenda
  AGENDA: 'AGENDA',
  ADICIONAR_COMPROMISSO: 'ADICIONAR_COMPROMISSO',

  // Alarmes
  ALARMES: 'ALARMES',
  EDITAR_ALARME: 'EDITAR_ALARME',

  // Contatos
  CONTATOS: 'CONTATOS',
  EDITAR_CONTATO: 'EDITAR_CONTATO',

  // Lembretes
  LEMBRETES: 'LEMBRETES',
  EDITAR_LEMBRETE: 'EDITAR_LEMBRETE',

  // Perfil Familiar
  PERFIL_FAMILIAR: 'PERFIL_FAMILIAR',

  // Perfil Usuário
  PERFIL: 'PERFIL',
  EDITAR_PERFIL: 'EDITAR_PERFIL',

  // Acessibilidade / Configurações
  ACESSIBILIDADE: 'ACESSIBILIDADE',
};
